# Exported from Render on 2024-03-27T16:38:45Z
databases:
- name: whiz
  databaseName: whiz_wfsl
  user: whiz_wfsl_user
  plan: free
  region: ohio
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
